### PR TITLE
add coercions

### PR DESCRIPTION
**Pull request by ttriche**

### CODE REVIEW

**Comment by arcolombo** [comment]
might as well merge, but is this pertaining to Kexp to SummarizedExp ?   or another motivation?  what is hte purpose here?  tyvm

**Comment by ttriche** [comment]
SE <- as(kexp, "SummarizedExperiment")

kexp <- as(SE, "KallistoExperiment")

identical(kexp, SE)

# [1] TRUE

--t

**Comment by arcolombo** [comment]
merging

**Comment by arcolombo** [comment]
this function should not be exported FYI.

**Comment by arcolombo** [comment]
when I have the @export tag, the devtools::document fusses,  when I remove and update the namespace, the change installs correctly.  I also tested the function with the removal of the export tag.  so it appears the export(as,..) should not be in namespace... or does not work on my end.    FYI

**Comment by arcolombo** [comment]
these should not be identical should htey? the class is RangedSummarizedExp and the other KallistoExperiment,  not sure how you got identicall..... leaving open... for now...

**Comment by ttriche** [comment]
woops, should have been

identical(kexp, as(as(kexp, "SummarizedExperiment"), "KallistoExperiment"))

not sure how I aliased the two at some point.

--t

**Comment by arcolombo** [comment]
yes I was able to produce this on my end.  O.K.

**Pull request merged**
